# Generated by Django 2.2 on 2020-06-07 15:50

from django.db import migrations, models
import django.utils.timezone
import uuid


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# fuauth.migrations.0023_add_user_ids

class Migration(migrations.Migration):

    replaces = [('fuauth', '0001_initial'), ('fuauth', '0002_auto_20141211_2035'), ('fuauth', '0003_auto_20141221_1456'), ('fuauth', '0004_auto_20150703_2045'), ('fuauth', '0005_auto_20150703_2056'), ('fuauth', '0006_auto_20160315_0913'), ('fuauth', '0007_auto_20160504_1253'), ('fuauth', '0008_auto_20160506_1137'), ('fuauth', '0009_auto_20160507_1342'), ('fuauth', '0010_user_how_many_messages'), ('fuauth', '0011_auto_20170527_1258'), ('fuauth', '0012_auto_20170527_1317'), ('fuauth', '0013_auto_20170527_1320'), ('fuauth', '0014_auto_20170527_1322'), ('fuauth', '0015_auto_20170527_1334'), ('fuauth', '0016_auto_20170527_1335'), ('fuauth', '0017_auto_20170527_1337'), ('fuauth', '0018_auto_20170527_1339'), ('fuauth', '0019_auto_20181212_2035'), ('fuauth', '0020_auto_20200103_1639'), ('fuauth', '0021_auto_20200126_0654'), ('fuauth', '0022_user_id'), ('fuauth', '0023_add_user_ids'), ('fuauth', '0024_auto_20200329_1421')]

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(blank=True, max_length=35, null=True, verbose_name='your name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='your email address')),
                ('phone_number', models.CharField(max_length=10, verbose_name='your phone number')),
                ('carrier', models.CharField(choices=[('mms.att.net', 'AT&T'), ('vtext.com', 'Verizon'), ('pixmbl.com', 'Virgin'), ('messaging.sprintpcs.com', 'Sprint'), ('tmomail.net', 'T-Mobile'), ('mms.cricketwireless.net', 'Cricket'), ('mymetropcs.com', 'Metro PCS'), ('msg.fi.google.com', 'Project Fi'), ('text.republicwireless.com', 'Republic Wireless'), ('tmomail.net', 'US Mobile')], default='pixmbl.com', max_length=100, verbose_name='carrier')),
                ('user_timezone', models.CharField(choices=[('HI', 'Hawaii'), ('AK', 'Alaska'), ('PC', 'Pacific'), ('MT', 'Mountain'), ('CN', 'Central'), ('EA', 'Eastern'), ('AT', 'Atlantic')], default='PC', max_length=2)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin        site', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the user should be treated as active.        Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('receive_newsletter', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, db_index=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('receiving_messages', models.BooleanField(default=True)),
                ('how_many_messages', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, max_length=1)),
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
