# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-29 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuauth', '0021_auto_20200126_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
